[project]
name = "teste"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "plotly-express>=0.4.1",
    "seaborn>=0.13.2",
    "streamlit>=1.40.2",
]
